" Default file encoding
set encoding=utf8

let &t_SI = "\<esc>[5 q" " I beam cursor for insert mode
let &t_EI = "\<esc>[2 q" " block cursor for normal mode - Change to 1 for blinking cursor
let &t_SR = "\<esc>[3 q" " underscore cursor for replace

let g:netrw_liststyle = 3
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'

set signcolumn="yes"
set number
set relativenumber
set cursorline
set showcmd
set showmatch
set ignorecase
set smartcase
set hidden
set confirm
set autoread
set ruler

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

filetype plugin indent on
filetype plugin on

" Save file as sudo with 'w!!'
cmap w!! w !sudo tee > /dev/null %

" Make 'set: list' show hidden charecters
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨,space:.

set clipboard=unnamedplus

set foldmethod=indent
set nofoldenable

"Remove trailing whitespaces on save
autocmd BufWritePre * :%s/\s\+$//e

"Window mangement
set splitright
set splitbelow

source ~/.vim/config/plugins.vim
source ~/.vim/config/keymaps.vim
