set line_numbers=relative
set vcs_aware true
set mouse_enabled true
set show_hidden true
set preview_files true

# Block ranger from opening files when going right
map l eval fm.execute_console('echo nop') if fm.thisfile.extension is not None else fm.move(right=1)
